server:
  port: 8103
  servlet:
    context-path: /api
    session:
      cookie:
        domain: xxx.xxx.xxx.xxx
        same-site: lax
        secure: false
spring:
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://xxx.xxx.xxx.xxx:3306/shierbi?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: shier
  # session 失效时间 30 天
  session:
    timeout: 2592000
    store-type: none
  # redis配置
  redis:
    port: 6379
    host: xxx.xxx.xxx.xxx
    database: 1
    password: xxx.xxx.xxx.xxx
  # rabbitmq 信息
  rabbitmq:
    host: xxx.xxx.xxx.xxx
    password: xxx.xxx.xxx.xxx
    username: shier
    port: 5672
mybatis-plus:
  configuration:
    # 生产环境关闭日志
    log-impl: ''
# 要使用的模型ID
ai:
  model:
    model-id: 1660100329896673281
# 鱼聪明SDK
yuapi:
  client:
    access-key: xxx.xxx.xxx.xxx
    secret-key: xxx.xxx.xxx.xxx
